name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the action on
  pull_request:
    branches:
      - main  # Set the branch you want to trigger the action on

jobs:
  run_notebook:
    runs-on: ubuntu-latest  # You can choose the appropriate runner based on your requirements

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the Python version you want to use

      - name: Install dependencies
        run: |
          pip install notebook  # Install Jupyter Notebook
          pip install nbconvert  # Install nbconvert to convert notebooks to other formats if needed
          pip install -r requirements.txt  # Install other project dependencies if needed

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Fake_News_Prediction.ipynb --output executed_notebook.ipynb
